from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, ConfigDict
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from config import get_settings
from database import get_db
from models import Asset, SentimentLabel, SentimentModel, SentimentRecord, SentimentSource
from services.data_collector import DataCollector

router = APIRouter(prefix="/api", tags=["social-data"])

SOCIAL_FEED_SOURCES = [
    SentimentSource.REDDIT,
    SentimentSource.STOCKTWITS,
    SentimentSource.NEWS,
    SentimentSource.TWITTER,
]


class SocialFeedItem(BaseModel):
    """Single social/news entry."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    source: SentimentSource
    text_snippet: str
    sentiment_score: Optional[float]
    sentiment_label: Optional[SentimentLabel]
    model_used: Optional[SentimentModel]
    confidence: Optional[float]
    source_url: Optional[str]
    author: Optional[str]
    created_at: datetime


class SocialStatsResponse(BaseModel):
    """Aggregated mention statistics per symbol."""

    symbol: str
    total_mentions: int
    by_source: Dict[str, int]
    positive_count: int
    negative_count: int
    neutral_count: int
    avg_sentiment_score: Optional[float]


class MarketSummaryResponse(BaseModel):
    """Latest market summary generated by Perplexity."""

    source: SentimentSource
    text_snippet: str
    created_at: datetime
    source_url: Optional[str]
    asset_symbol: Optional[str]


class MarketSummaryRefreshResponse(BaseModel):
    """Manual refresh result for Perplexity/Sonar summaries."""

    saved_count: int
    summary: Optional[MarketSummaryResponse]


@router.get("/social/{symbol}/feed", response_model=List[SocialFeedItem])
async def get_social_feed(
    symbol: str,
    limit: int = Query(default=50, ge=1, le=200),
    db: AsyncSession = Depends(get_db),
) -> List[SocialFeedItem]:
    """Return latest social/news records for one symbol."""
    asset = await _get_asset_by_symbol(db, symbol)
    if asset is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Asset nicht gefunden.")
    query = (
        select(SentimentRecord)
        .where(SentimentRecord.asset_id == asset.id, SentimentRecord.source.in_(SOCIAL_FEED_SOURCES))
        .order_by(SentimentRecord.created_at.desc())
        .limit(limit)
    )
    rows = list((await db.execute(query)).scalars().all())
    return [SocialFeedItem.model_validate(item) for item in rows]


@router.get("/social/{symbol}/stats", response_model=SocialStatsResponse)
async def get_social_stats(symbol: str, db: AsyncSession = Depends(get_db)) -> SocialStatsResponse:
    """Return mention statistics for one symbol."""
    asset = await _get_asset_by_symbol(db, symbol)
    if asset is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Asset nicht gefunden.")
    total = await _count_mentions(db, asset.id)
    by_source = await _count_by_source(db, asset.id)
    positive = await _count_by_label(db, asset.id, SentimentLabel.POSITIVE)
    negative = await _count_by_label(db, asset.id, SentimentLabel.NEGATIVE)
    neutral = await _count_by_label(db, asset.id, SentimentLabel.NEUTRAL)
    avg_query = select(func.avg(SentimentRecord.sentiment_score)).where(
        SentimentRecord.asset_id == asset.id,
        SentimentRecord.source.in_(SOCIAL_FEED_SOURCES),
    )
    avg_score = (await db.execute(avg_query)).scalar_one_or_none()
    return SocialStatsResponse(
        symbol=asset.symbol,
        total_mentions=total,
        by_source=by_source,
        positive_count=positive,
        negative_count=negative,
        neutral_count=neutral,
        avg_sentiment_score=float(avg_score) if avg_score is not None else None,
    )


@router.get("/market-summary", response_model=MarketSummaryResponse)
async def get_market_summary(db: AsyncSession = Depends(get_db)) -> MarketSummaryResponse:
    """Return latest Perplexity market summary."""
    row = await _latest_perplexity_record(db, require_global=True)
    if row is None:
        row = await _latest_perplexity_record(db, require_global=False)
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Keine Market Summary vorhanden.")
    return _summary_from_row(row)


@router.post("/market-summary/refresh", response_model=MarketSummaryRefreshResponse)
async def refresh_market_summary(db: AsyncSession = Depends(get_db)) -> MarketSummaryRefreshResponse:
    """Run one manual Perplexity refresh for immediate AI summaries."""
    if not get_settings().perplexity_api_key:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="PERPLEXITY_API_KEY fehlt.")

    collector = DataCollector()
    try:
        saved_count = await collector.collect_perplexity_summaries()
    finally:
        await collector.shutdown()

    row = await _latest_perplexity_record(db, require_global=True)
    if row is None:
        row = await _latest_perplexity_record(db, require_global=False)
    return MarketSummaryRefreshResponse(
        saved_count=saved_count,
        summary=_summary_from_row(row) if row is not None else None,
    )


async def _get_asset_by_symbol(db: AsyncSession, symbol: str) -> Optional[Asset]:
    query = select(Asset).where(Asset.symbol == symbol.upper().strip())
    return (await db.execute(query)).scalar_one_or_none()


async def _count_mentions(db: AsyncSession, asset_id: int) -> int:
    query = select(func.count(SentimentRecord.id)).where(
        SentimentRecord.asset_id == asset_id,
        SentimentRecord.source.in_(SOCIAL_FEED_SOURCES),
    )
    return int((await db.execute(query)).scalar_one())


async def _count_by_source(db: AsyncSession, asset_id: int) -> Dict[str, int]:
    query = (
        select(SentimentRecord.source, func.count(SentimentRecord.id))
        .where(SentimentRecord.asset_id == asset_id, SentimentRecord.source.in_(SOCIAL_FEED_SOURCES))
        .group_by(SentimentRecord.source)
    )
    rows = (await db.execute(query)).all()
    return {source.value: int(count) for source, count in rows}


async def _count_by_label(db: AsyncSession, asset_id: int, label: SentimentLabel) -> int:
    query = select(func.count(SentimentRecord.id)).where(
        SentimentRecord.asset_id == asset_id,
        SentimentRecord.source.in_(SOCIAL_FEED_SOURCES),
        SentimentRecord.sentiment_label == label,
    )
    return int((await db.execute(query)).scalar_one())


async def _latest_perplexity_record(db: AsyncSession, require_global: bool) -> Optional[tuple[SentimentRecord, Optional[str]]]:
    query = (
        select(SentimentRecord, Asset.symbol)
        .outerjoin(Asset, SentimentRecord.asset_id == Asset.id)
        .where(SentimentRecord.source == SentimentSource.PERPLEXITY)
        .order_by(SentimentRecord.created_at.desc())
        .limit(1)
    )
    if require_global:
        query = query.where(SentimentRecord.asset_id.is_(None))
    row = (await db.execute(query)).first()
    if row is None:
        return None
    return row[0], row[1]


def _summary_from_row(row: tuple[SentimentRecord, Optional[str]]) -> MarketSummaryResponse:
    record, symbol = row
    return MarketSummaryResponse(
        source=record.source,
        text_snippet=record.text_snippet,
        created_at=record.created_at,
        source_url=record.source_url,
        asset_symbol=symbol,
    )
